spring.application.name=lms

# server port
server.port=8086

# Automatic Restart
spring.devtools.restart.enabled=true

# Live Reload
spring.devtools.livereload.enabled=true

# mariaDB
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/lms
spring.datasource.username=lms
spring.datasource.password=1234

# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

logging.level.org.hibernate.type.descriptor.sql=trace

spring.thymeleaf.cache=false

#video.storage.path=file://C:/meta12/lms/videos/
#video.storage.path=file:///Users/macmini/Desktop/lms/videos/

# \uD30C\uC77C \uD558\uB098\uB2F9 \uCD5C\uB300 \uC6A9\uB7C9
spring.servlet.multipart.max-file-size=500MB
# \uC804\uCCB4 \uC694\uCCAD(\uD30C\uC77C \uC5EC\uB7EC\uAC1C \uD3EC\uD568) \uCD5C\uB300 \uC6A9\uB7C9
spring.servlet.multipart.max-request-size=500MB